**Revision of Concepts**

In [23]:
import numpy as np 
x = np.array([[1,2,3],[4,5,6]])
print("x:\n{}".format(x))
# print(x)

x:
[[1 2 3]
 [4 5 6]]


In [22]:
import sys
print(sys.path)

['d:\\Data_Science\\Machine Learning\\Book', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\python310.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\\lib', 'C:\\Users\\parth\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0', '', 'C:\\Users\\parth\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages', 'C:\\Users\\parth\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\win32', 'C:\\Users\\parth\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\win32\\lib', 'C:\\Users\\parth\\AppData\\L

##### Ensuring that all the modules are imported

In [3]:
import sys
print("Python version: {}".format(sys.version))

import pandas as pd
print("pandas version: {}".format(pd.__version__))

import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))

import numpy as np
print("NumPy version: {}".format(np.__version__))

import scipy as sp
print("SciPy version: {}".format(sp.__version__))

import IPython
print("IPython version: {}".format(IPython.__version__))

import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))

Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
pandas version: 2.0.2
matplotlib version: 3.7.1
NumPy version: 1.22.3
SciPy version: 1.10.1
IPython version: 8.14.0
scikit-learn version: 1.3.0


##### Playing around with iris dataset

In [2]:
import sklearn
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print(iris_dataset['DESCR'][:193]+ "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [12]:
## in format what happens is that the item specified in it takes place of {}
print("Target names: {}".format(iris_dataset['target_names']))
print("Type of data: {}".format(type(iris_dataset['data'])))
### format is one way of representing the information looks more clean
print("Shape of data: {}".format(iris_dataset['data'].shape))
print(f"Shape of the data: {iris_dataset['data'].shape}")

Target names: ['setosa' 'versicolor' 'virginica']
Type of data: <class 'numpy.ndarray'>
Shape of data: (150, 4)
Shape of the data: (150, 4)


In [15]:
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### Training and testing the data

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)
# X_train.shape , X_test.shape , y_train.shape , y_test.shape
iris_dataframe = pd.DataFrame(X_train,columns=iris_dataset.feature_names)
# pd.plotting.scatter_matrix(iris_dataframe,c = y_train, figsize=(15,15), marker='o', hist_kwds={'bins'},s=60,alpha=.8)


#### Building the KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [31]:

prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(iris_dataset['target_names'][prediction]))


Prediction: [0]
Predicted target name: ['setosa']


In [33]:
y_pred = knn.predict(X_test)
print(f"Test set prediction {y_pred}")
print("Test set score: {:.2f}".format(np.mean(y_pred== y_test)))

Test set prediction [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Test set score: 0.97


In [1]:
!pip install mglearn

  Using cached mglearn-0.2.0-py2.py3-none-any.whl (581 kB)
     -------------------------------------- 302.0/302.0 kB 3.7 MB/s eta 0:00:00
  Using cached imageio-2.31.1-py3-none-any.whl (313 kB)
  Using cached scikit_learn-1.3.0-cp310-cp310-win_amd64.whl (9.2 MB)
     ---------------------------------------- 44.0/44.0 MB 6.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: C:\Users\parth\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
